### ISSUE TITLE
[Feature]  jq support

### ISSUE THREAD

**Issue by jamiguet** [alf/ob-restclient.el#10]
It would be a really good addition if the mode supported a post-processing of the result via [jq](https://stedolan.github.io/jq/). This would enable for the consumption if the data in a more useful way.

As a complementary feature adding the possibility to tangle the code block into a runnable shell script using the export to curl functionality.

Is this something that you would see fit in ob-restclient?

**Comment by alf** [comment]
Yes, I can see how this can be useful.

**Comment by jamiguet** [comment]
Many Thanks for accepting the feature I will implement a version of it in
the next few weeks.

Kind regards.

**Comment by stardiviner** [comment]
Any update on this?

**Comment by jamiguet** [comment]
Not yet I have been busy with other things.
Mostly work but I will find the time to make progrss on it.
--
Juan Amiguet Vercher
Practising theorist
All-round geek
Polyglot polymath

+41(0)774867913

**Comment by alf** [comment]
Please re-open the issue if you make any progress. I won’t be implementing this, so I’m closing it for now.

**Comment by qzdl** [comment]
note this implementation from es-mode https://github.com/dakrone/es-mode/blob/cde5cafcbbbd57db6d38ae7452de626305bba68d/ob-elasticsearch.el#L110-L116

**Comment by alf** [comment]
Thank you, that’s very helpful. I’ll try to make some time for looking at this during the holidays.

**Comment by qzdl** [comment]
sure thing dude, I just made an implementation along these lines, will open a PR 

``` elisp
(defun org-babel-execute:restclient (body params)
  "Execute a block of Restclient code with org-babel.
This function is called by `org-babel-execute-src-block'"
  (message "executing Restclient source code block")
  (with-temp-buffer
    (let ((results-buffer (current-buffer))
          (restclient-same-buffer-response t)
          (restclient-same-buffer-response-name (buffer-name))
          (display-buffer-alist
           (cons
            '("\\*temp\\*" display-buffer-no-window (allow-no-window . t))
            display-buffer-alist)))

      (insert (buffer-name))
      (with-temp-buffer
        (dolist (p params)
          (let ((key (car p))
                (value (cdr p)))
            (when (eql key :var)
              (insert (format ":%s = <<\n%s\n#\n" (car value) (cdr value))))))
        (insert body)
	(goto-char (point-min))
	(delete-trailing-whitespace)
	(goto-char (point-min))
        (restclient-http-parse-current-and-do
         'restclient-http-do (org-babel-restclient--raw-payload-p params) t))

      (while restclient-within-call
        (sleep-for 0.05))

      (goto-char (point-min))
      (when (search-forward (buffer-name) nil t)
        (error "Restclient encountered an error"))

      (when (or (org-babel-restclient--return-pure-payload-result-p params)
                (assq :noheaders params)
                (assq :jq params))
        (org-babel-restclient--hide-headers))

      (when-let* ((jq-header (assoc :jq params))
                  (jq-path "jq"))
        (shell-command-on-region
         (point-min)
         (point-max)
         (format "%s %s" jq-path (shell-quote-argument (cdr jq-header)))
         (current-buffer)
         t))

      (when (not (org-babel-restclient--return-pure-payload-result-p params))
        (org-babel-restclient-wrap-result))
      
      (buffer-string))))
```
