### ISSUE TITLE
[Feature] Copy Curl Command from Org File

### ISSUE THREAD

**Issue by justinbarclay** [alf/ob-restclient.el#13]
Do you know of anyway to introduce or hack ob-restclient to be able to generate curl commands for you? My use case is I'm abstracting away some data generation to outside of a restclient block (like auth credentials), then passing that data in as a variable. I would like to be able to quickly generate curl commands for either further documentation and to easily share with coworkers.

**Comment by jamiguet** [comment]
In el mode elastic search mode it does support tangling and if the file
extension is sh it generates the equivalent curl command.

Also in pure rest mode, not inside orgg, ctrl-c ctrl-k will copy to the
clipboard the equivalent curl command.

**Comment by alf** [comment]
Sorry for the long delay in replying here.

I don’t see this as something ob-restclient should support. Rather you should open the source block in restclient mode using C-‘ and use copy the curl command from there.
