### ISSUE TITLE
pure payload hangs

### ISSUE THREAD

**Issue by titaniumbones** [alf/ob-restclient.el#16]
I'm accessing an API that returns an xml response. I'd like to pass it as a variable to another block for modification, so I don't want to wrap it in a source block. However, the regexp searches in `org-babel-restclient-pure-payload-result` hang indefinitely when I add `:results value`.  You can see it with a block like this, which works fine until :results value is added to the headers:

```http
:baseurl = https://api.zotero.org
GET :baseurl/groups/2250068/items/top?format=bib
```
Any way I can just get access to the whole raw buffer? 

Thanks for htis too, it's awesome!

**Comment by alf** [comment]
The result is created in a temporary buffer named `  *temp*`. This buffer is deleted when we're done, so to access it you need to enter the debugger. 

`*toggle-debug-on-quit*` for instance, and then when it hangs, you can switch to this buffer. access this buffer. Note the leading space in the buffer name.
