### ISSUE TITLE
#+END_SRC line is appended to the output without a newline

### ISSUE THREAD

**Issue by philipsd6** [alf/ob-restclient.el#17]
For example, the results from this org-mode block:
```org
* Get a list of my repositories
#+NAME: github-repositories
#+BEGIN_SRC restclient :var token=token
  GET https://api.github.com/user/repos?type=owner
  User-Agent: emacs27/restclient.el
  Authorization: Basic :token
#+END_SRC
```
Look like this:
```json
#+RESULTS: github-repositories
#+BEGIN_SRC js
[{"id": 123, ...}, {...}]#+END_SRC
```
Which breaks folding, and messes up subsequent org-mode blocks.

**Comment by alf** [comment]
I'm not able to reproduce this. Have you changed `org-babel-default-header-args:restclient`? If so, what are you using?

**Comment by alf** [comment]
Seems this is reproducible if we introduce hooks as per #19.
