### ISSUE TITLE
Add header argument for showing an specific amount of lines

### ISSUE THREAD

**Issue by rodrigo-morales-1** [alf/ob-restclient.el#23]
Let's suppose that an specific endpoint of the API returns more than 1000000 lines. It is highly likely that someone wouldn't like to have all those lines inserted in the Org Mode file.

I don't know how to limit the number of lines, so I make the following proposal: Add a `:lines` header argument for limiting the number of lines that would be inserted in the results of evaluation. Additionally, add the end of the response, we can add `(output limited to n lines)`.

**Comment by alf** [comment]
This one is too specific and out of scope. I suggest you solve this using `run-hooks`, for instance like so:

```
GET http://example.com
-> run-hook (progn (forward-line 1000) (delete-region (point) (point-max)))
```
