### ISSUE TITLE
restclient headers ?

### ISSUE THREAD

**Issue by olymk2** [alf/ob-restclient.el#7]
just curious if its possible to specify a headers block like you would in restclient mode ?
something like the below example.

myapi = http://myapi/

#+BEGIN_SRC restclient
GET myapi/test
#+END_SRC

**Comment by novoid** [comment]
As far as I know, the Org way would be using `:var` parameters as stated on http://orgmode.org/manual/var.html#var

So your example would be:

```
#+BEGIN_SRC restclient :var myapi="http://myapi/"
GET :myapi/test
#+END_SRC
```

I'd appreciate this feature as well because parameters could be defined in heading parameters as well.

Just for completeness: a currently working example with in-block parameters is:
```
#+BEGIN_SRC restclient
:myapi = http://myapi/

GET :myapi/test
#+END_SRC
```

**Comment by olymk2** [comment]
Thats close but from what i can tell these examples only apply to a single block so you need to specify the url for each block.

reading the var docs it looks like you can use a list or table with #+NAME: but it does not mention a single value so i am not sure if i could use that to specify the url globally.

**Comment by novoid** [comment]
Try and put your URL into a property of a heading and use it as input for :var 

This might work.

**Comment by olymk2** [comment]
Tried this and var does not seem to pick up apiurl :/

    #+PROPERTY: apiurl http://172.17.0.22:8097/bmis-gateway-api/v1.0
    #+BEGIN_SRC restclient :var myapi=apiurl
    GET :myapi/test
    #+END_SRC

**Comment by freckletonj** [comment]
Hey thanks for this! I love org, I love restclient, so this is great!

So, I came across this same problem, wanting define variables (especially `host` and `headers`) once, and then eval an HTTP request from non-connected code blocks.

I'm a bit new to using this stack of tools, but is there a way of using `session`s?

I tried, but if I eval a block with just headers, no request, it enters an infinite loop (`C-g` to get out)...

An alternative, although slightly less satisfying, would be if I could get `:results output` ("scripting mode") to work, but it still only outputs the last http req.

**Comment by dariuskramer** [comment]
@olymk2 The syntax you used is deprecated since *2013-06-23*. This works for me:
``` org
#+PROPERTY: header-args:restclient :var myapi="http://myapi"

#+BEGIN_SRC restclient
GET :myapi/test
#+END_SRC
```

Or if you want the variable only visible in a subtree:
``` org
* Headline
   :PROPERTRIES:
   :header-args:restclient: :var myapi="http://myapi"
   :END:

   #+BEGIN_SRC restclient
    GET :myapi/test
   #+END_SRC
```

See [this](https://org-babel.readthedocs.io/en/latest/header-args/#buffer-or-file-level-header-arguments) for an explanation

**Comment by olymk2** [comment]
Great thanks for that @dkrmr now i just need an opportunity to try it out :)

**Comment by alf** [comment]
Thanks @dkrm0, I believe that closes the issue. @olymk2 let me know if I’m mossing something.
